### ISSUE TITLE
simulation error 

### ISSUE THREAD

**Issue by F1nsk** [DronesForBlood/DronesForBlood#73]
```
[ERROR] [1544012991.364229, 139.740000]: bad callback: <bound method GcsMasterNode.pathplanner_newplan_callback of <gcs_master.gcs_master.GcsMasterNode object at 0x7fb4ebb3e2e8>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/finsk/catkin_ws/DronesForBlood/software/gcs/src/gcs_master/src/gcs_master/gcs_master.py", line 346, in pathplanner_newplan_callback
    self.next_wp_epoch = int(data.waypoints[0].param4)
IndexError: list index out of range


``` continues to fly after  

```

[ERROR] [1544013496.657115]: bad callback: <bound method GcsMasterNode.pathplanner_newplan_callback of <gcs_master.gcs_master.GcsMasterNode object at 0x7fc5e9a9a898>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/finsk/catkin_ws/DronesForBlood/software/gcs/src/gcs_master/src/gcs_master/gcs_master.py", line 346, in pathplanner_newplan_callback
    self.next_wp_epoch = int(data.waypoints[0].param4)
IndexError: list index out of range

```

**Comment by F1nsk** [comment]
does not crash, the GCS

**Comment by F1nsk** [comment]
```
[ERROR] [1544013496.657115]: bad callback: <bound method GcsMasterNode.pathplanner_newplan_callback of <gcs_master.gcs_master.GcsMasterNode object at 0x7fc5e9a9a898>>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/finsk/catkin_ws/DronesForBlood/software/gcs/src/gcs_master/src/gcs_master/gcs_master.py", line 346, in pathplanner_newplan_callback
    self.next_wp_epoch = int(data.waypoints[0].param4)
IndexError: list index out of range

```

**Comment by jlrandulfe** [comment]
Is this fixed @F1nsk? Close it if yes
